version: '3'

volumes:
  node1_data:
  node2_data:

networks:
  cassandra_network:
    driver: bridge

services:
  node1:
    image: cassandra:latest
    container_name: node-1
    restart: always
    hostname: node1
    environment:
      - CASSANDRA_SEEDS=node1
      - CASSANDRA_CLUSTER_NAME=my_cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
    volumes:
      - node1_data:/var/lib/cassandra
    networks:
      - cassandra_network

  node2:
    image: cassandra:latest
    container_name: node-2
    restart: always
    hostname: node2
    environment:
      - CASSANDRA_SEEDS=node1
      - CASSANDRA_CLUSTER_NAME=my_cluster
      - CASSANDRA_DC=dc2
      - CASSANDRA_RACK=rack2
    volumes:
      - node2_data:/var/lib/cassandra
    networks:
      - cassandra_network
